// Comprehensive Indian meal database with nutrition information

export interface Meal {
  id: string;
  name: string;
  nameHindi?: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  isVegetarian: boolean;
  mealType: "breakfast" | "lunch" | "dinner" | "snack";
  dietTypes: ("Low Carb" | "High Protein" | "Balanced")[];
  ingredients: string[];
  image?: string;
}

export const indianMeals: Meal[] = [
  // ===== BREAKFAST - VEGETARIAN =====
  {
    id: "b-v-1",
    name: "Poha with Vegetables",
    nameHindi: "सब्ज़ी पोहा",
    description: "Flattened rice cooked with onions, peanuts, and vegetables",
    calories: 280,
    protein: 8,
    carbs: 45,
    fats: 8,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Balanced"],
    ingredients: ["Flattened rice", "Onions", "Peanuts", "Turmeric", "Green chillies", "Curry leaves"],
  },
  {
    id: "b-v-2",
    name: "Idli Sambar",
    nameHindi: "इडली सांभर",
    description: "Steamed rice cakes served with lentil soup and coconut chutney",
    calories: 320,
    protein: 12,
    carbs: 55,
    fats: 6,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Rice", "Urad dal", "Toor dal", "Vegetables", "Sambar powder", "Coconut"],
  },
  {
    id: "b-v-3",
    name: "Moong Dal Cheela",
    nameHindi: "मूंग दाल चीला",
    description: "Savory lentil pancakes with green chutney",
    calories: 220,
    protein: 16,
    carbs: 25,
    fats: 7,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Moong dal", "Onions", "Green chillies", "Ginger", "Coriander"],
  },
  {
    id: "b-v-4",
    name: "Besan Cheela",
    nameHindi: "बेसन चीला",
    description: "Gram flour pancakes with onions and tomatoes",
    calories: 250,
    protein: 14,
    carbs: 28,
    fats: 9,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Gram flour", "Onions", "Tomatoes", "Green chillies", "Coriander"],
  },
  {
    id: "b-v-5",
    name: "Upma",
    nameHindi: "उपमा",
    description: "Semolina porridge with vegetables and mustard seeds",
    calories: 300,
    protein: 9,
    carbs: 48,
    fats: 10,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Balanced"],
    ingredients: ["Semolina", "Onions", "Carrots", "Peas", "Mustard seeds", "Curry leaves"],
  },
  {
    id: "b-v-6",
    name: "Paneer Bhurji",
    nameHindi: "पनीर भुर्जी",
    description: "Scrambled cottage cheese with spices and vegetables",
    calories: 280,
    protein: 18,
    carbs: 8,
    fats: 20,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Paneer", "Onions", "Tomatoes", "Green chillies", "Turmeric"],
  },
  {
    id: "b-v-7",
    name: "Dosa with Chutney",
    nameHindi: "दोसा",
    description: "Crispy rice and lentil crepe with coconut chutney",
    calories: 260,
    protein: 8,
    carbs: 40,
    fats: 8,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Balanced"],
    ingredients: ["Rice", "Urad dal", "Fenugreek", "Coconut", "Green chillies"],
  },
  {
    id: "b-v-8",
    name: "Oats Uttapam",
    nameHindi: "ओट्स उत्तपम",
    description: "Oatmeal pancake topped with vegetables",
    calories: 240,
    protein: 10,
    carbs: 35,
    fats: 7,
    isVegetarian: true,
    mealType: "breakfast",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Oats", "Yogurt", "Onions", "Tomatoes", "Green chillies"],
  },

  // ===== BREAKFAST - NON-VEGETARIAN =====
  {
    id: "b-nv-1",
    name: "Egg Bhurji",
    nameHindi: "अंडा भुर्जी",
    description: "Indian-style spiced scrambled eggs",
    calories: 220,
    protein: 16,
    carbs: 4,
    fats: 16,
    isVegetarian: false,
    mealType: "breakfast",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Eggs", "Onions", "Tomatoes", "Green chillies", "Turmeric", "Coriander"],
  },
  {
    id: "b-nv-2",
    name: "Egg Paratha",
    nameHindi: "अंडा पराठा",
    description: "Whole wheat flatbread stuffed with spiced eggs",
    calories: 380,
    protein: 18,
    carbs: 42,
    fats: 16,
    isVegetarian: false,
    mealType: "breakfast",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Whole wheat flour", "Eggs", "Onions", "Green chillies", "Ghee"],
  },
  {
    id: "b-nv-3",
    name: "Chicken Keema",
    nameHindi: "चिकन कीमा",
    description: "Minced chicken with spices, served with roti",
    calories: 350,
    protein: 28,
    carbs: 20,
    fats: 18,
    isVegetarian: false,
    mealType: "breakfast",
    dietTypes: ["High Protein", "Low Carb"],
    ingredients: ["Minced chicken", "Onions", "Tomatoes", "Ginger-garlic", "Garam masala"],
  },
  {
    id: "b-nv-4",
    name: "Omelette with Toast",
    nameHindi: "ऑमलेट टोस्ट",
    description: "Masala omelette with whole wheat toast",
    calories: 320,
    protein: 18,
    carbs: 28,
    fats: 15,
    isVegetarian: false,
    mealType: "breakfast",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Eggs", "Onions", "Tomatoes", "Whole wheat bread", "Butter"],
  },

  // ===== LUNCH - VEGETARIAN =====
  {
    id: "l-v-1",
    name: "Dal Tadka with Rice",
    nameHindi: "दाल तड़का चावल",
    description: "Yellow lentils tempered with spices, served with steamed rice",
    calories: 450,
    protein: 18,
    carbs: 72,
    fats: 10,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["Balanced"],
    ingredients: ["Toor dal", "Rice", "Cumin", "Garlic", "Tomatoes", "Ghee"],
  },
  {
    id: "l-v-2",
    name: "Rajma Chawal",
    nameHindi: "राजमा चावल",
    description: "Kidney beans curry with steamed rice",
    calories: 480,
    protein: 20,
    carbs: 75,
    fats: 12,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Kidney beans", "Rice", "Onions", "Tomatoes", "Ginger-garlic", "Spices"],
  },
  {
    id: "l-v-3",
    name: "Chole Bhature",
    nameHindi: "छोले भटूरे",
    description: "Spiced chickpeas with fried bread",
    calories: 580,
    protein: 18,
    carbs: 70,
    fats: 26,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["Balanced"],
    ingredients: ["Chickpeas", "Refined flour", "Onions", "Tomatoes", "Chole masala"],
  },
  {
    id: "l-v-4",
    name: "Palak Paneer with Roti",
    nameHindi: "पालक पनीर रोटी",
    description: "Cottage cheese in spinach gravy with whole wheat bread",
    calories: 420,
    protein: 22,
    carbs: 38,
    fats: 22,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["High Protein", "Balanced"],
    ingredients: ["Paneer", "Spinach", "Whole wheat flour", "Cream", "Spices"],
  },
  {
    id: "l-v-5",
    name: "Vegetable Biryani",
    nameHindi: "वेज बिरयानी",
    description: "Fragrant rice cooked with mixed vegetables and spices",
    calories: 420,
    protein: 12,
    carbs: 68,
    fats: 14,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["Balanced"],
    ingredients: ["Basmati rice", "Mixed vegetables", "Biryani masala", "Saffron", "Yogurt"],
  },
  {
    id: "l-v-6",
    name: "Paneer Tikka Wrap",
    nameHindi: "पनीर टिक्का रैप",
    description: "Grilled paneer in whole wheat wrap with mint chutney",
    calories: 380,
    protein: 24,
    carbs: 32,
    fats: 18,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["High Protein", "Balanced"],
    ingredients: ["Paneer", "Whole wheat roti", "Yogurt", "Mint", "Bell peppers"],
  },
  {
    id: "l-v-7",
    name: "Tofu Bhurji with Quinoa",
    nameHindi: "टोफू भुर्जी क्विनोआ",
    description: "Scrambled tofu served with protein-rich quinoa",
    calories: 340,
    protein: 22,
    carbs: 35,
    fats: 14,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["High Protein", "Low Carb"],
    ingredients: ["Tofu", "Quinoa", "Onions", "Tomatoes", "Turmeric", "Spices"],
  },
  {
    id: "l-v-8",
    name: "Stuffed Capsicum",
    nameHindi: "भरवां शिमला मिर्च",
    description: "Bell peppers stuffed with spiced paneer and vegetables",
    calories: 280,
    protein: 16,
    carbs: 18,
    fats: 18,
    isVegetarian: true,
    mealType: "lunch",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Bell peppers", "Paneer", "Onions", "Spices", "Peas"],
  },

  // ===== LUNCH - NON-VEGETARIAN =====
  {
    id: "l-nv-1",
    name: "Chicken Curry with Rice",
    nameHindi: "चिकन करी चावल",
    description: "Traditional chicken curry served with steamed rice",
    calories: 520,
    protein: 35,
    carbs: 55,
    fats: 18,
    isVegetarian: false,
    mealType: "lunch",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Chicken", "Rice", "Onions", "Tomatoes", "Ginger-garlic", "Spices"],
  },
  {
    id: "l-nv-2",
    name: "Fish Fry with Salad",
    nameHindi: "फिश फ्राई सलाद",
    description: "Crispy fried fish with fresh vegetable salad",
    calories: 380,
    protein: 32,
    carbs: 15,
    fats: 22,
    isVegetarian: false,
    mealType: "lunch",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Fish", "Semolina", "Spices", "Cucumber", "Tomatoes", "Onions"],
  },
  {
    id: "l-nv-3",
    name: "Chicken Biryani",
    nameHindi: "चिकन बिरयानी",
    description: "Aromatic rice layered with spiced chicken",
    calories: 580,
    protein: 32,
    carbs: 65,
    fats: 22,
    isVegetarian: false,
    mealType: "lunch",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Basmati rice", "Chicken", "Biryani masala", "Saffron", "Yogurt", "Onions"],
  },
  {
    id: "l-nv-4",
    name: "Egg Curry with Roti",
    nameHindi: "अंडा करी रोटी",
    description: "Boiled eggs in spiced tomato gravy with whole wheat bread",
    calories: 420,
    protein: 22,
    carbs: 40,
    fats: 20,
    isVegetarian: false,
    mealType: "lunch",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Eggs", "Whole wheat flour", "Onions", "Tomatoes", "Spices"],
  },
  {
    id: "l-nv-5",
    name: "Grilled Chicken Salad",
    nameHindi: "ग्रिल्ड चिकन सलाद",
    description: "Tandoori grilled chicken with fresh greens and yogurt dressing",
    calories: 320,
    protein: 38,
    carbs: 12,
    fats: 14,
    isVegetarian: false,
    mealType: "lunch",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Chicken breast", "Lettuce", "Cucumber", "Tomatoes", "Yogurt", "Mint"],
  },
  {
    id: "l-nv-6",
    name: "Mutton Keema with Peas",
    nameHindi: "मटन कीमा मटर",
    description: "Minced mutton cooked with green peas and spices",
    calories: 450,
    protein: 35,
    carbs: 18,
    fats: 28,
    isVegetarian: false,
    mealType: "lunch",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Minced mutton", "Peas", "Onions", "Tomatoes", "Ginger-garlic"],
  },

  // ===== DINNER - VEGETARIAN =====
  {
    id: "d-v-1",
    name: "Khichdi with Kadhi",
    nameHindi: "खिचड़ी कढ़ी",
    description: "Rice and lentil porridge with yogurt-based curry",
    calories: 380,
    protein: 14,
    carbs: 58,
    fats: 12,
    isVegetarian: true,
    mealType: "dinner",
    dietTypes: ["Balanced"],
    ingredients: ["Rice", "Moong dal", "Yogurt", "Gram flour", "Turmeric", "Cumin"],
  },
  {
    id: "d-v-2",
    name: "Roti with Aloo Gobi",
    nameHindi: "रोटी आलू गोभी",
    description: "Whole wheat bread with potato and cauliflower curry",
    calories: 350,
    protein: 10,
    carbs: 52,
    fats: 12,
    isVegetarian: true,
    mealType: "dinner",
    dietTypes: ["Balanced"],
    ingredients: ["Whole wheat flour", "Potatoes", "Cauliflower", "Cumin", "Turmeric"],
  },
  {
    id: "d-v-3",
    name: "Paneer Tikka with Salad",
    nameHindi: "पनीर टिक्का सलाद",
    description: "Grilled cottage cheese with fresh vegetable salad",
    calories: 320,
    protein: 24,
    carbs: 12,
    fats: 22,
    isVegetarian: true,
    mealType: "dinner",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Paneer", "Yogurt", "Bell peppers", "Onions", "Cucumber", "Mint"],
  },
  {
    id: "d-v-4",
    name: "Mixed Dal with Jeera Rice",
    nameHindi: "मिक्स दाल जीरा राइस",
    description: "Mixed lentils with cumin-flavored rice",
    calories: 420,
    protein: 18,
    carbs: 65,
    fats: 10,
    isVegetarian: true,
    mealType: "dinner",
    dietTypes: ["Balanced"],
    ingredients: ["Mixed lentils", "Rice", "Cumin", "Ghee", "Garlic", "Tomatoes"],
  },
  {
    id: "d-v-5",
    name: "Vegetable Soup with Multigrain Bread",
    nameHindi: "वेजिटेबल सूप मल्टीग्रेन ब्रेड",
    description: "Hot vegetable soup with toasted multigrain bread",
    calories: 250,
    protein: 10,
    carbs: 38,
    fats: 8,
    isVegetarian: true,
    mealType: "dinner",
    dietTypes: ["Balanced", "Low Carb"],
    ingredients: ["Mixed vegetables", "Multigrain bread", "Pepper", "Herbs"],
  },
  {
    id: "d-v-6",
    name: "Mushroom Matar",
    nameHindi: "मशरूम मटर",
    description: "Mushrooms and peas in spiced gravy with roti",
    calories: 300,
    protein: 14,
    carbs: 35,
    fats: 12,
    isVegetarian: true,
    mealType: "dinner",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Mushrooms", "Peas", "Whole wheat flour", "Onions", "Tomatoes"],
  },
  {
    id: "d-v-7",
    name: "Cauliflower Rice Stir-fry",
    nameHindi: "गोभी राइस स्टिर-फ्राई",
    description: "Low-carb cauliflower rice with vegetables and paneer",
    calories: 260,
    protein: 18,
    carbs: 15,
    fats: 16,
    isVegetarian: true,
    mealType: "dinner",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Cauliflower", "Paneer", "Bell peppers", "Soy sauce", "Ginger"],
  },

  // ===== DINNER - NON-VEGETARIAN =====
  {
    id: "d-nv-1",
    name: "Tandoori Chicken with Salad",
    nameHindi: "तंदूरी चिकन सलाद",
    description: "Grilled spiced chicken with fresh salad",
    calories: 350,
    protein: 38,
    carbs: 10,
    fats: 18,
    isVegetarian: false,
    mealType: "dinner",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Chicken", "Yogurt", "Tandoori masala", "Lemon", "Onions", "Cucumber"],
  },
  {
    id: "d-nv-2",
    name: "Fish Curry with Rice",
    nameHindi: "मछली करी चावल",
    description: "Bengali-style fish curry with steamed rice",
    calories: 450,
    protein: 30,
    carbs: 50,
    fats: 16,
    isVegetarian: false,
    mealType: "dinner",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Fish", "Rice", "Mustard oil", "Turmeric", "Green chillies", "Tomatoes"],
  },
  {
    id: "d-nv-3",
    name: "Chicken Tikka with Mint Chutney",
    nameHindi: "चिकन टिक्का पुदीना चटनी",
    description: "Grilled chicken chunks with fresh mint chutney",
    calories: 300,
    protein: 35,
    carbs: 8,
    fats: 14,
    isVegetarian: false,
    mealType: "dinner",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Chicken", "Yogurt", "Mint", "Coriander", "Spices", "Lemon"],
  },
  {
    id: "d-nv-4",
    name: "Egg Fried Rice",
    nameHindi: "एग फ्राइड राइस",
    description: "Indo-Chinese style fried rice with eggs and vegetables",
    calories: 420,
    protein: 18,
    carbs: 55,
    fats: 14,
    isVegetarian: false,
    mealType: "dinner",
    dietTypes: ["Balanced"],
    ingredients: ["Rice", "Eggs", "Mixed vegetables", "Soy sauce", "Spring onions"],
  },
  {
    id: "d-nv-5",
    name: "Prawn Masala",
    nameHindi: "प्रॉन मसाला",
    description: "Spiced prawns in coconut gravy with roti",
    calories: 380,
    protein: 28,
    carbs: 30,
    fats: 18,
    isVegetarian: false,
    mealType: "dinner",
    dietTypes: ["High Protein", "Balanced"],
    ingredients: ["Prawns", "Coconut milk", "Whole wheat flour", "Onions", "Tomatoes"],
  },

  // ===== SNACKS - VEGETARIAN =====
  {
    id: "s-v-1",
    name: "Roasted Chana",
    nameHindi: "भुने चने",
    description: "Crunchy roasted chickpeas with spices",
    calories: 150,
    protein: 9,
    carbs: 22,
    fats: 4,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["Balanced", "High Protein"],
    ingredients: ["Chickpeas", "Chaat masala", "Lemon"],
  },
  {
    id: "s-v-2",
    name: "Masala Buttermilk",
    nameHindi: "मसाला छाछ",
    description: "Spiced yogurt drink with cumin and mint",
    calories: 80,
    protein: 4,
    carbs: 8,
    fats: 3,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["Low Carb", "Balanced"],
    ingredients: ["Yogurt", "Cumin", "Mint", "Salt", "Water"],
  },
  {
    id: "s-v-3",
    name: "Fruit Chaat",
    nameHindi: "फ्रूट चाट",
    description: "Mixed fruits with chaat masala",
    calories: 120,
    protein: 2,
    carbs: 28,
    fats: 1,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["Balanced"],
    ingredients: ["Apple", "Banana", "Pomegranate", "Chaat masala", "Lemon"],
  },
  {
    id: "s-v-4",
    name: "Paneer Cubes",
    nameHindi: "पनीर क्यूब्स",
    description: "Grilled paneer cubes with mint chutney",
    calories: 180,
    protein: 14,
    carbs: 4,
    fats: 13,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Paneer", "Mint", "Yogurt", "Spices"],
  },
  {
    id: "s-v-5",
    name: "Sprouts Salad",
    nameHindi: "स्प्राउट्स सलाद",
    description: "Mixed sprouts with onions, tomatoes, and lemon",
    calories: 140,
    protein: 10,
    carbs: 18,
    fats: 3,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["High Protein", "Low Carb", "Balanced"],
    ingredients: ["Mixed sprouts", "Onions", "Tomatoes", "Lemon", "Chaat masala"],
  },
  {
    id: "s-v-6",
    name: "Dhokla",
    nameHindi: "ढोकला",
    description: "Steamed gram flour cake with green chutney",
    calories: 160,
    protein: 7,
    carbs: 25,
    fats: 4,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["Balanced"],
    ingredients: ["Gram flour", "Yogurt", "Mustard seeds", "Green chillies", "Coriander"],
  },
  {
    id: "s-v-7",
    name: "Mixed Nuts",
    nameHindi: "मिक्स्ड नट्स",
    description: "Assorted dry fruits and nuts",
    calories: 200,
    protein: 6,
    carbs: 10,
    fats: 16,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Almonds", "Cashews", "Walnuts", "Raisins"],
  },
  {
    id: "s-v-8",
    name: "Cucumber Raita",
    nameHindi: "खीरा रायता",
    description: "Yogurt with cucumber and cumin",
    calories: 90,
    protein: 5,
    carbs: 8,
    fats: 4,
    isVegetarian: true,
    mealType: "snack",
    dietTypes: ["Low Carb", "Balanced"],
    ingredients: ["Yogurt", "Cucumber", "Cumin", "Mint", "Salt"],
  },

  // ===== SNACKS - NON-VEGETARIAN =====
  {
    id: "s-nv-1",
    name: "Boiled Egg Whites",
    nameHindi: "उबले अंडे का सफेद",
    description: "Protein-rich egg whites with black pepper",
    calories: 70,
    protein: 14,
    carbs: 1,
    fats: 0,
    isVegetarian: false,
    mealType: "snack",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Egg whites", "Black pepper", "Salt"],
  },
  {
    id: "s-nv-2",
    name: "Chicken Seekh Kebab",
    nameHindi: "चिकन सीख कबाब",
    description: "Grilled minced chicken skewers",
    calories: 180,
    protein: 22,
    carbs: 4,
    fats: 9,
    isVegetarian: false,
    mealType: "snack",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Minced chicken", "Onions", "Ginger-garlic", "Spices", "Mint"],
  },
  {
    id: "s-nv-3",
    name: "Fish Tikka",
    nameHindi: "फिश टिक्का",
    description: "Grilled fish chunks with Indian spices",
    calories: 160,
    protein: 24,
    carbs: 3,
    fats: 6,
    isVegetarian: false,
    mealType: "snack",
    dietTypes: ["Low Carb", "High Protein"],
    ingredients: ["Fish", "Yogurt", "Tandoori masala", "Lemon", "Mint"],
  },
];

// Helper function to get meals by type and preferences
export function getMealsByType(
  mealType: "breakfast" | "lunch" | "dinner" | "snack",
  isVegetarian: boolean,
  dietType: string
): Meal[] {
  return indianMeals.filter((meal) => {
    const matchesType = meal.mealType === mealType;
    const matchesVeg = isVegetarian ? meal.isVegetarian : true;
    const matchesDiet = meal.dietTypes.includes(dietType as any);
    return matchesType && matchesVeg && matchesDiet;
  });
}

// Get fallback meals if not enough matches for diet type
export function getMealsByTypeWithFallback(
  mealType: "breakfast" | "lunch" | "dinner" | "snack",
  isVegetarian: boolean,
  dietType: string
): Meal[] {
  let meals = getMealsByType(mealType, isVegetarian, dietType);
  
  // If not enough meals, include "Balanced" as fallback
  if (meals.length < 3 && dietType !== "Balanced") {
    const balancedMeals = getMealsByType(mealType, isVegetarian, "Balanced");
    const existing = new Set(meals.map(m => m.id));
    meals = [...meals, ...balancedMeals.filter(m => !existing.has(m.id))];
  }
  
  return meals;
}
